Data annotations
brainchildservices/BrainchildHMS pull request #4
Opened 2021-09-10 15:57 UTC by sneha-brainchild

2021-09-11 05:26 UTC, rohithkrajan requested changes
Some comments are repeating

2021-09-11 05:26 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Class1.cs
> +namespace Brainchild.HMS.Core
This has to be deleted

2021-09-11 05:26 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Billing.cs
> +    public Payment Payment { get; set ;}
One billing can have multiple payment. Advance or additional charges etc

2021-09-11 05:26 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Booking.cs
> +    public DateTime CancelDate { get; set; }
Cancelled Date

2021-09-11 05:26 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Booking.cs
> +    public int status { get; set; }
Status s should be capital

2021-09-11 05:26 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/ChargeType.cs
> +    public List<Charge> Charges { get; set; }
We don't need this here. It's just a type definition

2021-09-11 05:26 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Guest.cs
> +    public string Name { get; set; }
Why I am seeing repeated comments. Already asked to change to Guest name.prefix column name with table name where ever it makes sense

2021-09-11 05:26 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Payment.cs
> +    public List<Billing> Billings { get; set; }
One to one, right? One payment should be associated with one bill

2021-09-11 05:26 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/PaymentType.cs
> +    public List<Payment> Payments { get; set; }
No need here

2021-09-11 05:26 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/RoomBooking.cs
> +public class RoomBooking
This should be an enum.so probably short datatype

2021-09-11 05:26 UTC, rohithkrajan commented on src/Brainchild.HMS.Data/Class1.cs
> +namespace Brainchild.HMS.Data
Remove this

2021-09-11 05:31 UTC, sneha-brainchild commented on src/Brainchild.HMS.Core/Models/Guest.cs
> +    public string Name { get; set; }
By mistake, I will correct it

2021-09-11 05:43 UTC, sneha-brainchild commented on src/Brainchild.HMS.Core/Models/ChargeType.cs
> +    public List<Charge> Charges { get; set; }
Ok

2021-09-11 06:51 UTC, sneha-brainchild commented on src/Brainchild.HMS.Core/Models/Billing.cs
> +    public Payment Payment { get; set ;}
done

2021-09-15 12:12 UTC, rohithkrajan requested changes
- Why so many sub properties added unnecessarily making objects complicated

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Billing.cs
> +    public int? HotelID { get; set; }
Why is this nullable int? Hotel I'd is always mandatory?

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Billing.cs
> +    public int? HotelID { get; set; }
Why do we need hotelid if booking is linked

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/CurrencyCode.cs
> +        public string CurrencyCodes { get; set; }
No plural required

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/CurrencyCode.cs
> +        public List<Charge> Charges { get; set; }
No need of this link

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Guest.cs
> +    public int HotelID { get; set; }
Why do we need this? Already linked via booking

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Hotel.cs
> +    public int TenantID { get; set; }
Did you check orchard core db

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Hotel.cs
> +    public List<Billing> Billing { get; set; }
Why do we need this

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Hotel.cs
> +    public List<Booking> Bookings { get; set; }
Why we need this

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Hotel.cs
> +    public List<Guest> Guests { get; set; }
Why we need this

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Hotel.cs
> +    public List<Tax> Taxes { get; set; }
Why

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Hotel.cs
> +    public List<PaymentType> PaymentTypes { get; set; }
Why

2021-09-15 12:12 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Hotel.cs
> +    public List<CurrencyCode> CurrencyCodes { get; set; }
Why

2021-09-15 16:44 UTC, rohithkrajan requested changes
Some minor comments

2021-09-15 16:44 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Currency.cs
> +        public int CurrencyCodeId { get; set; }
This should currencyId

2021-09-15 16:44 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Charge.cs
> +    [ForeignKey("CurrencyCodeId")]
This should be currencyId

2021-09-15 16:44 UTC, rohithkrajan commented on src/Brainchild.HMS.Core/Models/Room.cs
> +
We need to differentiate with hotelid

2021-09-15 17:00 UTC, rohithkrajan requested changes
One last change . sorry

2021-09-15 17:07 UTC, sneha-brainchild commented on src/Brainchild.HMS.Core/Models/Currency.cs
> +        [Column(TypeName = "varchar(1000)")]
yes it is 3 letter

2021-09-15 17:16 UTC, rohithkrajan approved these changes
Looks good

2021-09-15 17:22 UTC, merged